#DO NOT EDIT this file manually, changes will be overwritten
# This file is managed by Terraform and should not be edited directly.
# Variables for VPC module
#ONLY EDIT IF YOU WANT TO INTRODUCE NEW INPUTS VARIBLES in ./module/vpc
variable "cidr-range" {
  description = "CIDR block for the VPC"
  type        = string
  default     = ""
}

variable "private_subnets" {
  description = "Map of private subnet names to AZ index"
  type        = map(number)
  default = {
    "restrictated-subnet" = 0
  }
}

variable "public_subnets" {
  description = "Map of private subnet names to AZ index"
  type        = map(number)
  default = {
    "application-subnet" = 1
  }
}
