#DO NOT EDIT this file manually, changes will be overwritten
#This file is managed by Terraform and should not be edited directly.
#Variables for EC2 module
#APPLY CHNAGES TO variables.tf IN module/ec2

variable "ami_id" {
  description = "AMI ID to Provision Server"
  type        = string
}

variable "security_groups" {
  default = []
  type    = list(string)
}

variable "associate_public_ip" {
  description = "To attach Public Address"
  type        = bool
  default     = true
}

variable "subnet_id" {
  description = "Subnet id"
  type        = string
}

variable "instance_type" {
  description = "EC2 instance type"
  type        = string
}

variable "root_block_device" {
  description = "Root block device configuration"
  type = object({
    volume_type = string
    volume_size = number
    encrypted   = bool
    kms_key_id  = string
  })
  default = {
    volume_type = "gp2"
    volume_size = 10
    encrypted   = false
    kms_key_id  = null
  }
}

variable "environment" {
  description = "Choose Environment DEV/PROD"
  type        = string
  default     = "Dev"
}

variable "my_ip" {
  description = "Your public IP in CIDR format to allow access (e.g. 203.0.113.45/32). Must be set when applying."
  type        = string
  default     = "0.0.0.0/0" # my ip -var 'my_ip_cidr=192.168.56.1/32'
}