#DO NOT EDIT this file manually, changes will be overwritten
# This file is managed by Terraform and should not be edited directly.
# Variables for EC2 module
#APPLY CHNAGES TO variables.tf IN module/ec2
variable "ami_id" {
  description = "AMI ID to Provision Server"
  type        = string
}

variable "security_groups" {
  default = []
  type    = list(string)
}

variable "associate_public_ip" {
  description = "To attach Public Address"
  type        = bool
  default     = true
}

variable "subnet_id" {
  description = "Subnet id"
  type        = string
}

variable "instance_type" {
  description = "EC2 instance type"
  type        = string
}

variable "root_block_device" {
  description = "Root block device configuration"
  type = object({
    volume_type = string
    volume_size = number
    encrypted   = bool
    kms_key_id  = string
  })
  default = {
    volume_type = ""
    volume_size = ""
    encrypted   = ""
    kms_key_id  = ""
  }
}
