#DO NOT EDIT this file manually, changes will be overwritten
#This file is managed by Terraform and should not be edited directly.
#Variables for EC2 module
#APPLY CHNAGES TO variables.tf IN module/ec2

variable "ami_id" {
  description = "AMI ID to Provision Server"
  type        = string
  default     = "ami-0360c520857e3138f"
}

variable "security_group" {
  default     = []
  description = "List of Security Group IDs to attach to the instance"
  type        = list(string)
}

variable "associate_public_ip" {
  description = "To attach Public Address"
  type        = bool
  default     = true
}

variable "subnet_id" {
  description = "Subnet id"
  type        = string
  default     = ""
}

variable "instance_type" {
  description = "EC2 instance type"
  type        = string
  default     = "t2.micro"
}

variable "root_block_device" {
  description = "Root block device configuration"
  type = object({
    volume_type = string
    volume_size = number
    encrypted   = bool
    kms_key_id  = string
  })
  default = {
    volume_type = "gp2"
    volume_size = 10
    encrypted   = false
    kms_key_id  = null
  }
}

variable "server_type" {
  type        = string
  description = "DEV/DBS/APP/TST"

}

variable "created_by" {
  description = "Admin id"
  type        = string
  default     = "Terrraform-Admin"
}
