name: Security Scan-Checkov

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  checkov:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Checkov scan
        uses: bridgecrewio/checkov-action@master
        with:
          directory: ./terraform/main-infra   # path to your Terraform code
          framework: terraform
          output_format: sarif
          output_file_path: results.sarif

      - name: Upload results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
