name: Terraform Deploy

on:
  push:
    branches: ["main"]
    paths:
      - 'env/**'
jobs:
  terraform:
    name: "Terraform  Deploy"
    runs-on: ubuntu-latest
    
    permissions:
      id-token: write
      contents: write
      pull-requests: write

    env:
      AWS_REGION: "us-east-1"

    steps:
      - name: "Checkout GitHub repository"
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5
      
      - name: "Check Code Linting"
        uses: terraform-linters/setup-tflint@v1
        with:
          tflint_version: v0.60.0

      - name: "Run TFLint"
        run: tflint --version && tflint
        
      - name: Install tfsec and Run Scan
        run: |
          curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash
          tfsec --version
          tfsec .

      - name: "Terraform Init"
        run: terraform init
        
      - name: "Terraform fmt"
        run: terraform fmt
      
      - name: "Terraform Validate"
        run: terraform validate

      - name: "Terraform Plan"
        run: terraform plan -out=tfplan -var-file="dev.tfvars"

      - name: "Apply Changes to Infra"
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve tfplan


    